name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Workaround for fix issues with install
      run: |
        sudo gem install apt-spy2
        sudo apt-spy2 check
        sudo apt-spy2 fix --commit
        sudo apt-get update    
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get qt
      run: sudo apt-get install -y --no-install-recommends qtdeclarative5-dev libqt5svg5-dev qml-module-qtgraphicaleffects qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings libqt5websockets5-dev qtmultimedia5-dev libqt5multimedia5-plugins qml-module-qtmultimedia libvlccore-dev libvlc-dev
    - name: run qmake
      run: qmake -makefile -o src/Makefile src/AniLibria.pro
    - name: run make
      run: make -C src

