name: Flatpak x86_64 Build

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: anilibria.flatpak
        manifest-path: tv.anilibria.app.yml
        cache-key: flatpak-builder-${{ github.sha }}
